version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ekaterinas97/foodgram_backend1
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: ekaterinas97/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: ekaterinas97/foodgram_gateway
    env_file: .env
    ports:
      - "9010:80"
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend
